// <auto-generated />
using System;
using GameServer.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240920123717_AddShop")]
    partial class AddShop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameServer.DB.AccountGameDb", b =>
                {
                    b.Property<int>("AccountGameDbId")
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JwtToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountGameDbId");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.ToTable("AccountGame");
                });

            modelBuilder.Entity("GameServer.DB.ItemDataDb", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ItemDataDbid")
                        .HasColumnType("int");

                    b.Property<int>("maxCount")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ItemDataDbid")
                        .IsUnique();

                    b.ToTable("ItemData");
                });

            modelBuilder.Entity("GameServer.DB.ItemDb", b =>
                {
                    b.Property<int>("ItemDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemDbId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<bool>("Equipped")
                        .HasColumnType("bit");

                    b.Property<int?>("OwnerDbId")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("ItemDbId");

                    b.HasIndex("OwnerDbId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("GameServer.DB.MapDb", b =>
                {
                    b.Property<int>("MapDbId")
                        .HasColumnType("int");

                    b.Property<int>("MaxX")
                        .HasColumnType("int");

                    b.Property<int>("MaxY")
                        .HasColumnType("int");

                    b.Property<int>("MinX")
                        .HasColumnType("int");

                    b.Property<int>("MinY")
                        .HasColumnType("int");

                    b.Property<string>("TileInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MapDbId");

                    b.HasIndex("MapDbId")
                        .IsUnique();

                    b.ToTable("MapInfo");
                });

            modelBuilder.Entity("GameServer.DB.MonsterDataDb", b =>
                {
                    b.Property<int>("MonsterDataDbid")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<float>("Speed")
                        .HasColumnType("real");

                    b.Property<int>("TotalExp")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MonsterDataDbid");

                    b.HasIndex("MonsterDataDbid")
                        .IsUnique();

                    b.ToTable("Monster");
                });

            modelBuilder.Entity("GameServer.DB.PlayerDb", b =>
                {
                    b.Property<int>("PlayerDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerDbId"));

                    b.Property<int>("AccountDbId")
                        .HasColumnType("int");

                    b.Property<int>("AccountGameDbId")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int>("CurMap")
                        .HasColumnType("int");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("PosX")
                        .HasColumnType("real");

                    b.Property<float>("PosY")
                        .HasColumnType("real");

                    b.Property<float>("PosZ")
                        .HasColumnType("real");

                    b.Property<float>("Speed")
                        .HasColumnType("real");

                    b.Property<int>("TotalExp")
                        .HasColumnType("int");

                    b.HasKey("PlayerDbId");

                    b.HasIndex("AccountGameDbId");

                    b.HasIndex("PlayerName")
                        .IsUnique();

                    b.ToTable("Player");
                });

            modelBuilder.Entity("GameServer.DB.RewardDataDb", b =>
                {
                    b.Property<int>("RewardDataDbid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RewardDataDbid"));

                    b.Property<int?>("OwnerDbId")
                        .HasColumnType("int");

                    b.Property<int>("count")
                        .HasColumnType("int");

                    b.Property<int>("itemId")
                        .HasColumnType("int");

                    b.Property<int>("probability")
                        .HasColumnType("int");

                    b.HasKey("RewardDataDbid");

                    b.HasIndex("OwnerDbId");

                    b.HasIndex("RewardDataDbid")
                        .IsUnique();

                    b.ToTable("RewardData");
                });

            modelBuilder.Entity("GameServer.DB.ServerDb", b =>
                {
                    b.Property<int>("ServerDbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServerDbId"));

                    b.Property<int>("BusyScore")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.HasKey("ServerDbId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServerInfo");
                });

            modelBuilder.Entity("GameServer.DB.ShopDb", b =>
                {
                    b.Property<int>("ShopDbId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShopDbId");

                    b.HasIndex("ShopDbId")
                        .IsUnique();

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("GameServer.DB.ShopProductDb", b =>
                {
                    b.Property<int>("ShopProductDbId")
                        .HasColumnType("int");

                    b.Property<int>("CAmount")
                        .HasColumnType("int");

                    b.Property<int>("CType")
                        .HasColumnType("int");

                    b.Property<int>("PId")
                        .HasColumnType("int");

                    b.Property<int?>("ShopDbId")
                        .HasColumnType("int");

                    b.HasKey("ShopProductDbId");

                    b.HasIndex("ShopDbId");

                    b.HasIndex("ShopProductDbId")
                        .IsUnique();

                    b.ToTable("ShopProduct");
                });

            modelBuilder.Entity("GameServer.DB.ItemDb", b =>
                {
                    b.HasOne("GameServer.DB.PlayerDb", "Owner")
                        .WithMany("Items")
                        .HasForeignKey("OwnerDbId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GameServer.DB.PlayerDb", b =>
                {
                    b.HasOne("GameServer.DB.AccountGameDb", "AccountGame")
                        .WithMany("Players")
                        .HasForeignKey("AccountGameDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountGame");
                });

            modelBuilder.Entity("GameServer.DB.RewardDataDb", b =>
                {
                    b.HasOne("GameServer.DB.MonsterDataDb", "Owner")
                        .WithMany("rewards")
                        .HasForeignKey("OwnerDbId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GameServer.DB.ShopProductDb", b =>
                {
                    b.HasOne("GameServer.DB.ShopDb", null)
                        .WithMany("ShopProducts")
                        .HasForeignKey("ShopDbId");
                });

            modelBuilder.Entity("GameServer.DB.AccountGameDb", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("GameServer.DB.MonsterDataDb", b =>
                {
                    b.Navigation("rewards");
                });

            modelBuilder.Entity("GameServer.DB.PlayerDb", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GameServer.DB.ShopDb", b =>
                {
                    b.Navigation("ShopProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
